version: '3.1'
services:
  mysql:
    container_name: ssi_mysql
    restart: always
    platform: linux/x86_64
    image: mysql:5.7
    command: --init-file /data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DOCKER_MYSQL_DATABASE}
    volumes:
    - ./data/db:/var/lib/mysql
    - ./data/init.sql:/data/application/init.sql
    ports:
      - "3306:3306"